// This file was autogenerated by Claude during a refactor
import { useState, useEffect, useMemo } from "react";
import debounce from "lodash/debounce";
import {
  Autocomplete,
  TextField,
  CircularProgress,
  Box,
} from "@mui/material";

/**
 * Highlight the matched part of each option.
 * If `query` is empty, returns plain text.
 */
function highlight(text, query) {
  if (!query) return text;
  const parts = text.split(
    new RegExp(`(${query.replace(/[.*+?^${}()|[\\]\\]/g, "\\$&")})`, "gi")
  );
  return parts.map((part, i) =>
    part.toLowerCase() === query.toLowerCase() ? (
      <mark key={i} style={{ background: "none", color: "inherit" }}>
        {part}
      </mark>
    ) : (
      part
    )
  );
}

/**
 * SearchBar component.
 * - Debounced input update
 * - Loading spinner inside the dropdown
 * - Matching‑letter highlighting in options
 * - Uses MUI Autocomplete for accessibility
 */
export default function SearchBar({
  options = [],
  value = "",
  onChange = () => {},
  onClear = () => {},
  loading = false,
  disabled = false,
}) {
  const [input, setInput] = useState(value);
  const [rawOptions, setRawOptions] = useState(options);

  // Debounce the parent callback to avoid flooding
  const debouncedCallback = useMemo(() => debounce(onChange, 300), [onChange]);

  useEffect(() => {
    debouncedCallback(input);
    return () => debouncedCallback.cancel();
  }, [input, debouncedCallback]);

  // Keep local options in sync with prop
  useEffect(() => {
    setRawOptions(options);
  }, [options]);

  const handleClear = () => {
    setInput("{}");
    onClear();
  };

  return (
    <Autocomplete
      sx={{ width: 300 }}
      options={rawOptions}
      loading={loading}
      disabled={disabled}
      disableClearable
      inputValue={input}
      onInputChange={(_event, newInput) => setInput(newInput)}
      value={value}
      onChange={(_event, newValue) => {
        if (newValue) onChange(newValue);
      }}
      onClear={handleClear}
      filterOptions={(x) => x}
      renderInput={(params) => (
        <TextField
          {...params}
          label="Search products"
          variant="outlined"
          InputProps={{
            ...params.InputProps,
            endAdornment: (
              <>
                {loading ? <CircularProgress size={20} /> : null}
                {params.InputProps.endAdornment}
              </>
            ),
          }}
        />
      )}
      renderOption={(props, option, { inputValue, selected }) => (
        <Box component="li" sx={{ padding: 1, ...(selected && { background: "#f5f5f5" }) }} {...props}>
          {highlight(option, inputValue)}
        </Box>
      )}
      getOptionLabel={(option) => option}
    />
  );
}
